import styles from "./line-frame.module.css";

const LineFrame = () => {
  return (
    <div className={styles.lineFrame}>
      <div className={styles.lineFrameChild} />
      <header className={styles.rectangleParent}>
        <div className={styles.frameChild} />
        <div className={styles.delhiRollsLogo}>
          <div className={styles.home}>Home</div>
          <div className={styles.about}>about</div>
          <div className={styles.locations}>Locations</div>
        </div>
        <div className={styles.delhiRollsFinalLogo011}>
          <div className={styles.delhiRollsFinalLogo011Inner}>
            <div className={styles.delhiRollsParent}>
              <div className={styles.delhiRolls}>Delhi Rolls</div>
              <div className={styles.junctions}>Junctions</div>
            </div>
          </div>
          <div className={styles.delhiRollsFinalLogo011Child}>
            <div className={styles.locationTextParent}>
              <div className={styles.locationText}>
                <div className={styles.deliveryHoursGroup}>
                  <img
                    className={styles.uniqueTasteFrame}
                    alt=""
                    src="/unique-taste-frame.svg"
                  />
                  <img
                    className={styles.vectorIcon}
                    alt=""
                    src="/vector-1.svg"
                  />
                  <img
                    className={styles.rollinSinceFrame}
                    alt=""
                    src="/vector-2.svg"
                  />
                  <img
                    className={styles.vectorIcon1}
                    alt=""
                    src="/vector-3.svg"
                  />
                  <img
                    className={styles.rollinSinceFrame1}
                    alt=""
                    src="/vector-4.svg"
                  />
                  <img
                    className={styles.quickLinksFrame}
                    alt=""
                    src="/vector-5.svg"
                  />
                  <img
                    className={styles.rollinSinceFrame2}
                    alt=""
                    src="/vector-6.svg"
                  />
                  <img
                    className={styles.rollinSinceFrame3}
                    alt=""
                    src="/vector-7.svg"
                  />
                  <img
                    className={styles.contentFrameIcon}
                    alt=""
                    src="/vector-8.svg"
                  />
                  <img
                    className={styles.rectangleShapeIcon}
                    alt=""
                    src="/vector-9.svg"
                  />
                </div>
                <div className={styles.textNode}>
                  <img
                    className={styles.lineNodeIcon}
                    alt=""
                    src="/vector-10.svg"
                  />
                  <img className={styles.groupIcon} alt="" src="/group1.svg" />
                </div>
                <div className={styles.frameNode}>
                  <img
                    className={styles.groupIcon1}
                    alt=""
                    src="/group-1.svg"
                  />
                  <div className={styles.group}>
                    <img
                      className={styles.vectorIcon2}
                      alt=""
                      src="/vector-11.svg"
                    />
                    <div className={styles.clipPathGroup}>
                      <img className={styles.vectorIcon3} alt="" />
                    </div>
                    <div className={styles.clipPathGroup1}>
                      <img className={styles.vectorIcon4} alt="" />
                    </div>
                    <div className={styles.clipPathGroup2}>
                      <img className={styles.vectorIcon5} alt="" />
                    </div>
                    <div className={styles.clipPathGroup3}>
                      <img className={styles.vectorIcon6} alt="" />
                    </div>
                    <div className={styles.clipPathGroup4}>
                      <img className={styles.vectorIcon7} alt="" />
                    </div>
                    <div className={styles.clipPathGroup5}>
                      <img className={styles.vectorIcon8} alt="" />
                    </div>
                    <div className={styles.groupParent}>
                      <img
                        className={styles.groupIcon2}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon3}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon4}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon5}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon6}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon7}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon8}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon9}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon10}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon11}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon12}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon13}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon14}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon15}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon16}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon17}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon18}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon19}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon20}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon21}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon22}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon23}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon24}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon25}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon26}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon27}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon28}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon29}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon30}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon31}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon32}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon33}
                        alt=""
                        src="/group-33@2x.png"
                      />
                      <img
                        className={styles.groupIcon34}
                        alt=""
                        src="/group-34@2x.png"
                      />
                      <img
                        className={styles.groupIcon35}
                        alt=""
                        src="/group-35@2x.png"
                      />
                      <img
                        className={styles.groupIcon36}
                        alt=""
                        src="/group-36@2x.png"
                      />
                      <img
                        className={styles.groupIcon37}
                        alt=""
                        src="/group-37@2x.png"
                      />
                      <img
                        className={styles.groupIcon38}
                        alt=""
                        src="/group-38@2x.png"
                      />
                      <img
                        className={styles.groupIcon39}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon40}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon41}
                        alt=""
                        src="/group-41@2x.png"
                      />
                      <img
                        className={styles.groupIcon42}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon43}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon44}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon45}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon46}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon47}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon48}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon49}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon50}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon51}
                        alt=""
                        src="/group-51@2x.png"
                      />
                      <img
                        className={styles.groupIcon52}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon53}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon54}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon55}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon56}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon57}
                        alt=""
                        src="/group-57@2x.png"
                      />
                      <img
                        className={styles.groupIcon58}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon59}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon60}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon61}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon62}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon63}
                        alt=""
                        src="/group-63@2x.png"
                      />
                      <img
                        className={styles.groupIcon64}
                        alt=""
                        src="/group-64@2x.png"
                      />
                      <img
                        className={styles.groupIcon65}
                        alt=""
                        src="/group-65@2x.png"
                      />
                      <img
                        className={styles.groupIcon66}
                        alt=""
                        src="/group-66@2x.png"
                      />
                      <img
                        className={styles.groupIcon67}
                        alt=""
                        src="/group-67@2x.png"
                      />
                      <img
                        className={styles.groupIcon68}
                        alt=""
                        src="/group-68@2x.png"
                      />
                      <img
                        className={styles.groupIcon69}
                        alt=""
                        src="/group-69@2x.png"
                      />
                      <img
                        className={styles.groupIcon70}
                        alt=""
                        src="/group-70@2x.png"
                      />
                      <img
                        className={styles.groupIcon71}
                        alt=""
                        src="/group-71@2x.png"
                      />
                      <img
                        className={styles.groupIcon72}
                        alt=""
                        src="/group-72@2x.png"
                      />
                      <img
                        className={styles.groupIcon73}
                        alt=""
                        src="/group-73@2x.png"
                      />
                      <img
                        className={styles.groupIcon74}
                        alt=""
                        src="/group-74@2x.png"
                      />
                      <img
                        className={styles.groupIcon75}
                        alt=""
                        src="/group-75@2x.png"
                      />
                      <img
                        className={styles.groupIcon76}
                        alt=""
                        src="/group-76@2x.png"
                      />
                      <img
                        className={styles.groupIcon77}
                        alt=""
                        src="/group-77@2x.png"
                      />
                      <img
                        className={styles.groupIcon78}
                        alt=""
                        src="/group-78@2x.png"
                      />
                      <img
                        className={styles.groupIcon79}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon80}
                        alt=""
                        src="/group-80@2x.png"
                      />
                      <img
                        className={styles.groupIcon81}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon82}
                        alt=""
                        src="/group-2@2x.png"
                      />
                      <img
                        className={styles.groupIcon83}
                        alt=""
                        src="/group-83@2x.png"
                      />
                      <img
                        className={styles.groupIcon84}
                        alt=""
                        src="/group-84@2x.png"
                      />
                      <img
                        className={styles.groupIcon85}
                        alt=""
                        src="/group-85@2x.png"
                      />
                      <img
                        className={styles.groupIcon86}
                        alt=""
                        src="/group-86@2x.png"
                      />
                      <img
                        className={styles.groupIcon87}
                        alt=""
                        src="/group-87@2x.png"
                      />
                      <img
                        className={styles.groupIcon88}
                        alt=""
                        src="/group-88@2x.png"
                      />
                      <img
                        className={styles.groupIcon89}
                        alt=""
                        src="/group-89@2x.png"
                      />
                      <img
                        className={styles.groupIcon90}
                        alt=""
                        src="/group-90.svg"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className={styles.frameParent}>
                <div className={styles.groupGroup}>
                  <img
                    className={styles.groupIcon91}
                    alt=""
                    src="/group-91.svg"
                  />
                  <div className={styles.vectorParent}>
                    <img
                      className={styles.vectorIcon9}
                      alt=""
                      src="/vector-18.svg"
                    />
                    <img
                      className={styles.groupIcon92}
                      alt=""
                      src="/group-92@2x.png"
                    />
                  </div>
                </div>
                <div className={styles.quickLinksGroup}>
                  <img
                    className={styles.contactlessFrameIcon}
                    alt=""
                    src="/vector-19.svg"
                  />
                  <img
                    className={styles.locationFrameIcon}
                    alt=""
                    src="/vector-20.svg"
                  />
                  <img
                    className={styles.titleFrameIcon}
                    alt=""
                    src="/vector-21.svg"
                  />
                  <img
                    className={styles.delhiRollsFrame}
                    alt=""
                    src="/vector-22.svg"
                  />
                  <img
                    className={styles.titleFrameIcon1}
                    alt=""
                    src="/vector-23.svg"
                  />
                  <img
                    className={styles.vectorIcon10}
                    alt=""
                    src="/vector-24.svg"
                  />
                  <img
                    className={styles.titleFrameIcon2}
                    alt=""
                    src="/vector-25.svg"
                  />
                  <img
                    className={styles.titleFrameIcon3}
                    alt=""
                    src="/vector-26.svg"
                  />
                  <img
                    className={styles.clipPathGroup6}
                    alt=""
                    src="/vector-27.svg"
                  />
                  <img
                    className={styles.lineFrameIcon}
                    alt=""
                    src="/vector-28.svg"
                  />
                </div>
                <div className={styles.quickLinksFrameWrapper}>
                  <div className={styles.quickLinksFrame1}>
                    <img
                      className={styles.quickMenuFrame}
                      alt=""
                      src="/vector-29.svg"
                    />
                    <img
                      className={styles.groupIcon93}
                      alt=""
                      src="/group-93.svg"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.subscribeFrame}>
          <div className={styles.orderByUbereats}>Order By UberEats</div>
          <button className={styles.rectangleGroup}>
            <div className={styles.frameItem} />
            <div className={styles.viewFullMenu}>View Full Menu</div>
          </button>
        </div>
      </header>
      <div className={styles.lineFrameInner}>
        <div className={styles.frameWrapper}>
          <div className={styles.deliciousKathiRollParent}>
            <div className={styles.deliciousKathiRollContainer}>
              <p className={styles.delicious}>{`delicious `}</p>
              <p className={styles.kathi}>{`Kathi       Roll `}</p>
            </div>
            <div className={styles.wrapperVector1Parent}>
              <div className={styles.wrapperVector1}>
                <img
                  className={styles.wrapperVector1Child}
                  loading="eager"
                  alt=""
                  src="/vector-12.svg"
                />
              </div>
              <img
                className={styles.wepikExport20231222091818bkbIcon}
                alt=""
                src="/wepikexport20231222091818bkbs-1@2x.png"
              />
            </div>
          </div>
        </div>
      </div>
      <img
        className={styles.image1Icon}
        loading="eager"
        alt=""
        src="/image-1@2x.png"
      />
      <img
        className={styles.image2Icon}
        loading="eager"
        alt=""
        src="/image-2@2x.png"
      />
    </div>
  );
};

export default LineFrame;
